# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - unnecessary_new
    - prefer_final_fields
    - always_specify_types
    - public_member_api_docs
    - lines_longer_than_80_chars
    - type_annotate_public_apis
    - prefer_single_quotes
    - avoid_types_on_closure_parameters
    - unnecessary_this
    - prefer_is_empty
    - prefer_contains
    - avoid_annotating_with_dynamic
    - prefer_typing_uninitialized_variables
    - use_key_in_widget_constructors