name: salary_level_app
description: A Flutter app for diagnosing salary percentiles and negotiation leverage using public and real-time data.
publish_to: 'none' 

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  csv: ^6.0.0
  fl_chart: ^0.66.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/